### ISSUE TITLE
Overall Presentation

### ISSUE THREAD

**Issue by cviddy17** [Xarmanla/intro-data-capstone-biodiversity#2]
The presentation looks great! I love the color scheme used with your text and there was a good balance between text and charts.

In the future I would suggest to do a little bit more with the theming - Transition slides, other images, and maybe a different overall theme might have added an extra pop.

**Comment by Xarmanla** [comment]
Good suggestion on adding other images.  I wanted to concentrate on answering the questions regarding the data, rather than entertaining the reader.  I have visited many of the U.S. National Parks and could have related stories from my personal observations, but I decided to focus on the data in the files.  The presentation was keep simple because it was intended to be presented in a live setting..
